language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django>=1.8,<1.8.999"
  - DJANGO="django==1.7.7"

install:
 - if [[ $DJANGO == 'django==1.7.7' ]]; then pip install django_mptt==0.6.0; fi
 - pip install -r requirements/external_apps.txt
 - pip install -r requirements/extra_apps.txt
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - coverage run --source=basic_cms setup.py test

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="django==1.7.7"
    - python: "3.5"
      env: DJANGO="django==1.7.7"

after_success:
  - coverage report --omit="basic_cms/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
