language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.8 --use-mirrors"
  - DJANGO="django==1.7.5 --use-mirrors"

install:
 - pip install -r requirements/external_apps.txt --use-mirrors
 - pip install -r requirements/extra_apps.txt --use-mirrors
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - coverage run --source=basic_cms setup.py test

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="django==1.7.5 --use-mirrors"

after_success:
  - coverage report --omit="basic_cms/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
