language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django>=1.11.20,<1.11.999"

install:

 - pip install -r requirements/external_apps.txt
 - pip install -r requirements/extra_apps.txt
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - coverage run --source=basic_cms setup.py test

after_success:
  - coverage report --omit="basic_cms/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
